# Generated by Django 5.2.1 on 2025-05-27 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videojuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=50)),
                ('fecha_lanzamiento', models.DateField()),
                ('plataforma', models.CharField(max_length=50)),
                ('jugado', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
